mi:
  dropbox:
    root: "/forecast_mi"

    datasets_dir: "datasets"
    models_dir: "models_retrained"
    results_json: "model_results_retrain_test.json"

    forecasts_dir: "forecasts_next_96"
    forecast_history_long: "forecast_history_long.parquet"
    forecast_history_wide: "forecast_history_wide.parquet"
    forecast_errors: "forecast_errors.parquet"

  forecast:
    steps: 96
    freq: "15min"
    lookback_days: 10

  mercati:
    - "Italia (senza vincoli)"
    - "Calabria"
    - "Centro Nord"
    - "Centro Sud"
    - "Nord"
    - "Sardegna"
    - "Sicilia"
    - "Sud"
    - "Italia Coupling"
